# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Tiankuan (Felix) Wang
program: Bachelor of Computing Science
degree: Honors Degree
university: University of Alberta
email: tiankuan@ualberta.ca
personal_email: tiankwang@yahoo.com
# email_title: Email (Email title override)
phone: +1(825)-977-1966
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: U70-TK
instagram_username: felixwangggg
linkedin_username: felix-wang-75b0b824b

about_profile_image: images/Photo.jpg
about_content: |
  I am a scholar and developer who has experience using <mark>Python, Java, TypeScript</mark>, and modern web frameworks like <mark>React and NestJS</mark> for projects. My experience spans across both front-end and back-end development, utilizing tools such as <mark>Docker</mark> and databases like <mark>MySQL, PostgreSQL, and MongoDB</mark>. I also have a keen interest in <mark>Machine Learning</mark> and <mark>Software Engineering</mark>, applying advanced frameworks like <mark>Pytorch</mark> to solve complex problems. Fluent in both English and Chinese, I excel in <mark>multicultural environments</mark>, bringing strong <mark>communication skills, academic writing skills, and qualitative analysis</mark> skills to my work.

content:
  - title: Research Experience
    layout: list
    content:
      - layout: right
        border: weak  
        title: <a href="/assets/UG_STNN__SMC.pdf">UG-STNN Model</a>
        description: |
          Mentored by Dr. Zesheng Cheng and contributed to his research in UG-STNN model, which is a Spatial-Temporal Neural Network based on an unsupervised graph representation module for traffic flow prediction. The paper will be presented at the conference SMC 2024.
          
      - layout: right
        border: weak  
        title: <a href="/assets/STGCN(SVD).pdf">STGCN(SVD) Model</a>
        description: |
          Mentored by Dr. Zesheng Cheng and contributed substantially to his research in STGCN(SVD) model, which introduced a SVD-based denoising layer to the traditional STGCN model to enhance the performance of graph neural networks in traffic flow prediction.
          
      - layout: right
        border: weak  
        title: Software Management under COVID-19 Study
        description: |
          Mentored by Dr. Paul Ralph on an interview study about the hybrid working mode in Hybrid Software Engineering during COVID. Compared teams under hybrid working mode, co-located software engineering mode, and fully remote working mode. Second author of the unpublished paper “Hybrid Software Engineering trades Coordination and Trust for Flexibility and Cost Savings.”
          
      - layout: right
        border: weak  
        title: Clobber Game Conjecture Study
        description: |
          Mentored by Dr. Ryan Hayward on a Game Theory project about proving a conjecture mentioned in the paper “An introduction to Clobber” published in the Journal INTEGER. The project includes mathematical proving as well as developing an algorithm for solving an NP-Hard problem.

  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Software Engineer Intern
        sub_title: Haier Smart Home - Qingdao, China
        caption: July 2023 - August 2023
        description: |
          - Participated in the development of the speech control module for the Casarte (Haier) washing machine.
          - Contributed to the code of Haier's IoT packages, including the startup sound feature, voice-switching feature, sleep mode voice activation feature, and washing and drying voice activation feature.
          - Participated in group meetings to report project details and coordinate project progress with project managers.
          
      - layout: left
        title: Research Assistant
        sub_title: Dalhousie University Software Engineering Lab - Halifax, Canada
        caption: May 2022 - September 2022
        description: |
          - Worked on an interview study discussing the Software Industry's hybrid working mode during the COVID pandemic.
          - Supervised by award-winning computer scientist Dr. Paul Ralph.
          - Conducted interviews, collected data, and transcribed the information for analysis.
          - Presented research findings to groups of people.
          - Performed qualitative analysis of interview data.
          - Engaged in academic writing to contribute to scholarly discourse.

      - layout: left
        title: Web Development Intern
        sub_title: Qingdao Yuezhenq Electronic Technology Co., Ltd. - Qingdao, China
        caption: October 2020 - January 2021
        description: |
          - Worked on a Vocational School Education Management System project (Teacher's interface).
          - Wrote supporting code for web applications.
          - Evaluated code to ensure its validity, proper structure, compliance with industry standards, and compatibility with various browsers, devices, and operating systems.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Alberta
        sub_title: B.Sc. Computing Science (Honors)
        caption: September 2022 - June 2025 (Expected Graduation)
        description: |
          - Current GPA: 3.75/4
          - Relevant courses and skills:
            - Android development with Java (Gradle), software development principles and design patterns for robust and scalable mobile applications.
            - Course on cross-platform development using React Native, NestJS, and TypeScript, focusing on Agile methodologies and software management practices.
            - Database query implementation (SQLite, MongoDB) and database scaling and normalization.
            - Software quality improvement using Black Box testing, White Box testing, AB testing, and performance testing.
            - Searching and Planning in Artificial Intelligence, converting realistic scenarios into a Constraint Satisfaction Problem for AI algorithms to perform searching.

      - layout: top-right
        title: Dalhousie University
        sub_title: Bachelor of Computer Science
        caption: January 2022 - September 2022
        description: |
          - GPA: 4.3/4.3
          - Relevant courses and skills:
            - Course on using HTTP, CSS and JavaScript to build web pages, as well as basic network communication principles.
            - Use Python's data science libraries such as numpy, pandas, and matplotlib to perform data science analysis and data visualization.
            - Agile Development's philosophy, implementation methods, and basic management principles for software engineering teams.
            - Use tools such as Wiresharks to capture and analyze network packets, as well as the basic concepts and applications of cryptography.

      - layout: top-right
        title: The Australian National University
        sub_title: Bachelor of Information Technology
        caption: February 2020 - January 2022
        description: |
          - Relevant courses and skills:
            - Use Java to implement basic data structures and algorithms.
            - Use Haskell to get familiar with Functional Programming and implement game artificial intelligence algorithms in Game theory.
            - Use Assembly Language ARMv7 to code STM32 discovery kits. 

  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Discovery Kit Music Player
        sub_title: ARMv7, STM32 Discovery Kit
        quote: >
          A music player based on an STM32L476 discovery kit and programmed with ARMv7.
        description: |
          - Music will be played when users plug their headphones in, with three different tracks selectable using the Joycon. LED lights flash when the corresponding button is pressed.

      - layout: left
        border: weak
        title: QRCode Hunter
        sub_title: Java, Android, Android Studio, Firebase
        link: https://github.com/CMPUT301W23T46/IQDisabled
        link_text: GitHub Page
        quote: >
          An Android app built with Java (Gradle).
        description: |
          - Users can scan QR codes to obtain scores and compete with friends online, while a Google Maps API displays nearby "QRCode Hunter" users and their scores, and a leaderboard ranks all users' scores in descending order.

      - layout: left
        border: weak
        title: Smart Home
        sub_title: TypeScript, React Native, NestJS, PostgreSQL, Docker, NginX
        link: https://github.com/UAlberta-CMPUT401/f23project-simply-home
        link_text: GitHub Page
        quote: >
          A TypeScript project by a startup company aiming to manage home appliances and provide maintenance solutions.
        description: |
          - Uses React Native as a presentation layer, NginX and NestJS for business logic, and PostgreSQL for DB service. The project is dockerized and deployed on Cybera Cloud.
          - <a href="/assets/application-d49ddf88-380b-49c8-bdbb-542b2f4f912a.apk">APK file can be found here. </a>
      - layout: left
        border: weak
        title: AI-powered Ninuki Game
        sub_title: Python, Minimax, AlphaBeta, MCTS
        quote: >
          A Python project that allows human players to compete against AI opponents in a GoGui.
        description: |
          - The game features multiple levels of difficulty to cater to players of varying skill levels. AI opponents are implemented using different algorithms: a Minimax-based player for basic strategic moves, an Alpha-Beta pruning-based player for more efficient decision-making, and a Monte Carlo Tree Search (MCTS) player for advanced and probabilistic strategies.

  - title: Volunteer Experience
    layout: text
    content: |
      **Volunteer for Prairie Urban Farm: Summer Gardening.**
      - Participated in various summer gardening activities, including planting, watering, and maintaining garden beds, contributing to the community's food sustainability efforts. Worked with a diverse group of people, learning about urban farming practices and teamwork in a collaborative outdoor environment.
      - <img src="/images/volunteer1.jpg" alt="Volunteering picture1" width="400"/>
      - <img src="/images/volunteer2.jpg" alt="Volunteering picture2" width="400"/>
      **City of Edmonton: Drop-in Tree Planting Program.**
  
  - title: Awards
    layout: text
    content: |
      **2024 Dean's Honor Roll - University of Alberta Faculty of Science.**

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
